# Generated by Django 3.2.5 on 2021-07-19 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.IntegerField()),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('From', models.TimeField(default=django.utils.timezone.now)),
                ('To', models.TimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='', max_length=50)),
                ('destination', models.CharField(default='', max_length=50)),
                ('number_of_seats', models.IntegerField(default=0)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trip_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('books', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admins.train')),
            ],
        ),
    ]
